---
title: Senshu
baseurl: /senshu

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  senshu:
    output: true

defaults:
  - scope:
      path: '_senshu'
    values:
      layout: bin
